version: '3.9'

services:
  api-bank-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'bank'
    ports:
      - '15432:5432'
    volumes:
      - api-bank-data:/var/lib/postgresql/data
      - ./scripts/01-init-docker-databases.sql:/docker-entrypoint-initdb.d/01-init-docker-databases.sql

volumes:
  api-bank-data:
